### ISSUE TITLE
MELPA install conflicts with fountain-mode

### ISSUE THREAD

**Issue by cdr255** [mkjunker/abc-mode#3]
I've run into an [issue](https://github.com/rnkn/fountain-mode/issues/66) with it conflicting with another package (fountain mode) on MELPA. When both abc-mode and fountain-mode are installed from MELPA, fountain-mode fails to load. I don't know enough about elisp to really say why, though.

**Comment by rnkn** [comment]
Sorry, this was a bug with fountain-mode not abc-mode. Carry on.
